
package soap.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarRentServerService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/CarRent?wsdl")
public class CarRentServerService
    extends Service
{

    private final static URL CARRENTSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARRENTSERVERSERVICE_EXCEPTION;
    private final static QName CARRENTSERVERSERVICE_QNAME = new QName("http://soap/", "CarRentServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CarRent?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARRENTSERVERSERVICE_WSDL_LOCATION = url;
        CARRENTSERVERSERVICE_EXCEPTION = e;
    }

    public CarRentServerService() {
        super(__getWsdlLocation(), CARRENTSERVERSERVICE_QNAME);
    }

    public CarRentServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARRENTSERVERSERVICE_QNAME, features);
    }

    public CarRentServerService(URL wsdlLocation) {
        super(wsdlLocation, CARRENTSERVERSERVICE_QNAME);
    }

    public CarRentServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARRENTSERVERSERVICE_QNAME, features);
    }

    public CarRentServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarRentServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarRentServer
     */
    @WebEndpoint(name = "CarRentServerPort")
    public CarRentServer getCarRentServerPort() {
        return super.getPort(new QName("http://soap/", "CarRentServerPort"), CarRentServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarRentServer
     */
    @WebEndpoint(name = "CarRentServerPort")
    public CarRentServer getCarRentServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "CarRentServerPort"), CarRentServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARRENTSERVERSERVICE_EXCEPTION!= null) {
            throw CARRENTSERVERSERVICE_EXCEPTION;
        }
        return CARRENTSERVERSERVICE_WSDL_LOCATION;
    }

}
