
package soap.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarRentServer", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarRentServer {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "changeCarSpecifications", targetNamespace = "http://soap/", className = "soap.webservice.ChangeCarSpecifications")
    @ResponseWrapper(localName = "changeCarSpecificationsResponse", targetNamespace = "http://soap/", className = "soap.webservice.ChangeCarSpecificationsResponse")
    @Action(input = "http://soap/CarRentServer/changeCarSpecificationsRequest", output = "http://soap/CarRentServer/changeCarSpecificationsResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap/CarRentServer/changeCarSpecifications/Fault/IOException")
    })
    public void changeCarSpecifications(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "rentCar", targetNamespace = "http://soap/", className = "soap.webservice.RentCar")
    @ResponseWrapper(localName = "rentCarResponse", targetNamespace = "http://soap/", className = "soap.webservice.RentCarResponse")
    @Action(input = "http://soap/CarRentServer/rentCarRequest", output = "http://soap/CarRentServer/rentCarResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap/CarRentServer/rentCar/Fault/IOException")
    })
    public void rentCar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnFoundCars", targetNamespace = "http://soap/", className = "soap.webservice.ReturnFoundCars")
    @ResponseWrapper(localName = "returnFoundCarsResponse", targetNamespace = "http://soap/", className = "soap.webservice.ReturnFoundCarsResponse")
    @Action(input = "http://soap/CarRentServer/returnFoundCarsRequest", output = "http://soap/CarRentServer/returnFoundCarsResponse")
    public List<Object> returnFoundCars();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addNewCar", targetNamespace = "http://soap/", className = "soap.webservice.AddNewCar")
    @ResponseWrapper(localName = "addNewCarResponse", targetNamespace = "http://soap/", className = "soap.webservice.AddNewCarResponse")
    @Action(input = "http://soap/CarRentServer/addNewCarRequest", output = "http://soap/CarRentServer/addNewCarResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap/CarRentServer/addNewCar/Fault/IOException")
    })
    public void addNewCar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3)
        throws IOException_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "showAllCars", targetNamespace = "http://soap/", className = "soap.webservice.ShowAllCars")
    @ResponseWrapper(localName = "showAllCarsResponse", targetNamespace = "http://soap/", className = "soap.webservice.ShowAllCarsResponse")
    @Action(input = "http://soap/CarRentServer/showAllCarsRequest", output = "http://soap/CarRentServer/showAllCarsResponse")
    public void showAllCars();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnTotalCost", targetNamespace = "http://soap/", className = "soap.webservice.ReturnTotalCost")
    @ResponseWrapper(localName = "returnTotalCostResponse", targetNamespace = "http://soap/", className = "soap.webservice.ReturnTotalCostResponse")
    @Action(input = "http://soap/CarRentServer/returnTotalCostRequest", output = "http://soap/CarRentServer/returnTotalCostResponse")
    public int returnTotalCost();

    /**
     * 
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "backCar", targetNamespace = "http://soap/", className = "soap.webservice.BackCar")
    @ResponseWrapper(localName = "backCarResponse", targetNamespace = "http://soap/", className = "soap.webservice.BackCarResponse")
    @Action(input = "http://soap/CarRentServer/backCarRequest", output = "http://soap/CarRentServer/backCarResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap/CarRentServer/backCar/Fault/IOException")
    })
    public void backCar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.webservice.Car
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnObjCars", targetNamespace = "http://soap/", className = "soap.webservice.ReturnObjCars")
    @ResponseWrapper(localName = "returnObjCarsResponse", targetNamespace = "http://soap/", className = "soap.webservice.ReturnObjCarsResponse")
    @Action(input = "http://soap/CarRentServer/returnObjCarsRequest", output = "http://soap/CarRentServer/returnObjCarsResponse")
    public Car returnObjCars(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnTotalCars", targetNamespace = "http://soap/", className = "soap.webservice.ReturnTotalCars")
    @ResponseWrapper(localName = "returnTotalCarsResponse", targetNamespace = "http://soap/", className = "soap.webservice.ReturnTotalCarsResponse")
    @Action(input = "http://soap/CarRentServer/returnTotalCarsRequest", output = "http://soap/CarRentServer/returnTotalCarsResponse")
    public int returnTotalCars();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "clearFoundCars", targetNamespace = "http://soap/", className = "soap.webservice.ClearFoundCars")
    @ResponseWrapper(localName = "clearFoundCarsResponse", targetNamespace = "http://soap/", className = "soap.webservice.ClearFoundCarsResponse")
    @Action(input = "http://soap/CarRentServer/clearFoundCarsRequest", output = "http://soap/CarRentServer/clearFoundCarsResponse")
    public void clearFoundCars();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "showCertainCars", targetNamespace = "http://soap/", className = "soap.webservice.ShowCertainCars")
    @ResponseWrapper(localName = "showCertainCarsResponse", targetNamespace = "http://soap/", className = "soap.webservice.ShowCertainCarsResponse")
    @Action(input = "http://soap/CarRentServer/showCertainCarsRequest", output = "http://soap/CarRentServer/showCertainCarsResponse")
    public void showCertainCars(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
